name: CI Pipeline

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t devops-flask-app:latest .
          
      - name: Run Unit Tests (Optional)
        run: |
          echo "No tests yet, but this is where they would run! ✅"
